// AI assistant endpoint updated
// AI assistant endpoint updated
import { useEffect, useState } from "react";

import Map from "./Map";
import PollutionChart from "./PollutionChart";
import ForecastChart from "./ForecastChart";
import PollutionAlert from "./PollutionAlert";
import CitizenReport from "./CitizenReport";
import AdvancedAnalytics from "./AdvancedAnalytics";
import PollutionImageAnalysis from "./PollutionImageAnalysis";

import "./App.css";
import { useLocationData } from "./LocationContext";

const API_BASE = "https://bricsair.onrender.com";

const BRICS_CITIES = [
  {
    key: "bengaluru",
    name: "Bengaluru",
    country: "India",
    flag: "🇮🇳",
  },
  {
    key: "sao-paulo",
    name: "São Paulo",
    country: "Brazil",
    flag: "🇧🇷",
  },
  {
    key: "moscow",
    name: "Moscow",
    country: "Russia",
    flag: "🇷🇺",
  },
  {
    key: "beijing",
    name: "Beijing",
    country: "China",
    flag: "🇨🇳",
  },
  {
    key: "johannesburg",
    name: "Johannesburg",
    country: "South Africa",
    flag: "🇿🇦",
  },
];

function getAQIStatus(aqi) {
  const value = Number(aqi);

  if (value === 1) return "Good";
  if (value === 2) return "Fair";
  if (value === 3) return "Moderate";
  if (value === 4) return "Poor";
  if (value === 5) return "Very Poor";

  return "Unknown";
}

function getPM25Status(pm25) {
  const value = Number(pm25);

  if (value <= 12) return "Good";
  if (value <= 35) return "Moderate";
  if (value <= 55)
    return "Unhealthy for Sensitive Groups";
  if (value <= 150) return "Unhealthy";

  return "Very Unhealthy";
}

function Dashboard() {
  const {
    location,
    air,
    weather,
    prediction: contextPrediction,
    forecast,
    selectedCity,
    setSelectedCity,
    hasSelectedLocation,
    loadCity,
    searchLocation,
  } = useLocationData();

  const [searchText, setSearchText] = useState("");
  const [loading, setLoading] = useState(false);
  const [searching, setSearching] = useState(false);
  const [error, setError] = useState("");
  const [lastUpdated, setLastUpdated] = useState("");

  const [prediction, setPrediction] =
    useState(contextPrediction);

  const [predictionLoading, setPredictionLoading] =
    useState(false);

  const [predictionError, setPredictionError] =
    useState("");

  const [aiQuestion, setAiQuestion] = useState("");
const [aiAnswer, setAiAnswer] = useState("");
const [aiLoading, setAiLoading] = useState(false);
const [aiError, setAiError] = useState("");

  /*
   * --------------------------------------------------
   * LOAD PREDICTION FOR CURRENT CITY
   * --------------------------------------------------
   */

  useEffect(() => {
  let cancelled = false;

  async function loadDashboardPrediction() {
    // For searched locations, use the prediction
    // already generated by LocationContext.
    if (contextPrediction) {
      console.log(
        "DASHBOARD USING CONTEXT PREDICTION:",
        contextPrediction
      );

      if (!cancelled) {
        setPrediction(contextPrediction);
        setPredictionError("");
        setPredictionLoading(false);
      }

      return;
    }

    // No BRICS city selected and no searched-location prediction.
    if (!selectedCity) {
      if (!cancelled) {
        setPrediction(null);
        setPredictionError("");
        setPredictionLoading(false);
      }

      return;
    }

    try {
      if (!cancelled) {
        setPredictionLoading(true);
        setPredictionError("");
        setPrediction(null);
      }

      const response = await fetch(
        `${API_BASE}/api/prediction?city=${encodeURIComponent(
          selectedCity
        )}`,
        {
          method: "GET",
          headers: {
            Accept: "application/json",
          },
        }
      );

      if (!response.ok) {
        const errorData =
          await response.json().catch(() => ({}));

        throw new Error(
          errorData.error ||
            `Prediction API returned ${response.status}`
        );
      }

      const data = await response.json();

      console.log(
        "DASHBOARD BRICS PREDICTION:",
        data
      );

      if (!cancelled) {
        setPrediction(data);
        setPredictionError("");
      }
    } catch (error) {
      console.error(
        "Dashboard prediction error:",
        error
      );

      if (!cancelled) {
        setPrediction(null);
        setPredictionError(
          "AI prediction is temporarily unavailable."
        );
      }
    } finally {
      if (!cancelled) {
        setPredictionLoading(false);
      }
    }
  }

  loadDashboardPrediction();

  return () => {
    cancelled = true;
  };
}, [selectedCity, contextPrediction]);

  /*
   * --------------------------------------------------
   * INITIAL DASHBOARD
   * --------------------------------------------------
   */

  useEffect(() => {
    if (hasSelectedLocation) {
      return;
    }

    async function initializeDashboard() {
      try {
        setLoading(true);
        setError("");

        await loadCity("bengaluru");

        setLastUpdated(
          new Date().toLocaleTimeString()
        );
      } catch (error) {
        console.error(
          "Initial dashboard loading error:",
          error
        );

        setError(
          "Unable to load environmental data."
        );
      } finally {
        setLoading(false);
      }
    }

    initializeDashboard();

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [hasSelectedLocation]);

  /*
   * --------------------------------------------------
   * CHANGE BRICS CITY
   * --------------------------------------------------
   */

  async function handleCityChange(cityKey) {
    try {
      setLoading(true);
      setError("");

      setAiAnswer("");
      setAiError("");

      /*
       * Clear old prediction immediately so the
       * previous city's prediction is not displayed
       * while the new city is loading.
       */

      setPrediction(null);
      setPredictionError("");
      setPredictionLoading(true);

      await loadCity(cityKey);

      setSelectedCity(cityKey);

      setLastUpdated(
        new Date().toLocaleTimeString()
      );
    } catch (error) {
      console.error(
        "City loading error:",
        error
      );

      setError(
        "Unable to load environmental data."
      );
    } finally {
      setLoading(false);
    }
  }

  /*
   * --------------------------------------------------
   * SEARCH LOCATION
   * --------------------------------------------------
   */

  async function handleSearchLocation() {
    if (!searchText.trim()) {
      return;
    }

    try {
      setSearching(true);
      setError("");

      setAiAnswer("");
      setAiError("");

      setPrediction(null);
      setPredictionError("");

      await searchLocation(searchText);

      setLastUpdated(
        new Date().toLocaleTimeString()
      );

      setSearchText("");
    } catch (error) {
      console.error(
        "Location search error:",
        error
      );

      setError(
        "Location not found or environmental data unavailable."
      );
    } finally {
      setSearching(false);
    }
  }

  function handleSearchKeyDown(event) {
    if (event.key === "Enter") {
      handleSearchLocation();
    }
  }

  /*
   * --------------------------------------------------
   * AI ENVIRONMENTAL ASSISTANT
   * --------------------------------------------------
   */

  async function askAI() {
  if (!location || !air || !aiQuestion.trim()) {
    return;
  }

  try {
    setAiLoading(true);
    setAiError("");
    setAiAnswer("");

    const response = await fetch(
  `${API_BASE}/api/ai-assistant`,
  {
    method: "POST",
    headers: {
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      question: aiQuestion,
      location,
      airQuality: air,
      weather,
      prediction,
    }),
  }
);

    if (!response.ok) {
      const errorData =
        await response.json().catch(() => ({}));

      throw new Error(
        errorData.error ||
          "AI service unavailable"
      );
    }

    const data = await response.json();

    setAiAnswer(
      data.answer ||
        "No AI answer available."
    );
  } catch (error) {
    console.error(
      "AI assistant error:",
      error
    );

    setAiError(
      error.message ||
        "AI analysis is temporarily unavailable. Please try again."
    );
  } finally {
    setAiLoading(false);
  }
}

  /*
   * --------------------------------------------------
   * POLLUTION VALUES
   * --------------------------------------------------
   */

  const firstHotspot =
    air?.hotspots?.[0] || {};

  const pm25 = Number(
    firstHotspot.pm25 ??
      air?.pm25 ??
      0
  );

  const pm10 = Number(
    firstHotspot.pm10 ??
      air?.pm10 ??
      0
  );

  const no2 = Number(
    firstHotspot.no2 ??
      air?.no2 ??
      0
  );

  const so2 = Number(
    firstHotspot.so2 ??
      air?.so2 ??
      0
  );

  const co = Number(
    firstHotspot.co ??
      air?.co ??
      0
  );

  const o3 = Number(
    firstHotspot.o3 ??
      air?.o3 ??
      0
  );

  const aqi = Number(
    firstHotspot.aqi ??
      air?.aqi ??
      air?.main?.aqi ??
      0
  );

  const aqiStatus =
    getAQIStatus(aqi);

  const pm25Status =
    getPM25Status(pm25);

  const temperature =
    weather?.temperature ??
    weather?.temp ??
    weather?.main?.temp ??
    "--";

  const humidity =
    weather?.humidity ??
    weather?.main?.humidity ??
    "--";

  const windSpeed =
    weather?.windSpeed ??
    weather?.wind?.speed ??
    "--";

  const predictedPM25 =
    prediction?.predictedPM25 ??
    prediction?.prediction ??
    "--";

  /*
   * --------------------------------------------------
   * INITIAL LOADING SCREEN
   * --------------------------------------------------
   */

  if (loading && !air) {
    return (
      <div className="dashboard-container">

        <div className="dashboard-loading">

          <div className="dashboard-loader"></div>

          <h3>
            Loading BRICSense
          </h3>

          <p>
            Loading environmental intelligence...
          </p>

        </div>

      </div>
    );
  }

  return (
    <div className="dashboard-container">

      {/* =========================
          WELCOME
      ========================= */}

      <div className="dashboard-welcome">

        <div>

          <span className="dashboard-eyebrow">
            ENVIRONMENTAL INTELLIGENCE
          </span>

          <h2>
            BRICSense Dashboard
          </h2>

          <p>
            AI-powered air quality monitoring
            and environmental insights.
          </p>

        </div>

        {lastUpdated && (
          <div className="dashboard-updated">

            <span>
              LAST UPDATED
            </span>

            <strong>
              {lastUpdated}
            </strong>

          </div>
        )}

      </div>


      {/* =========================
          SEARCH
      ========================= */}

      <div className="dashboard-search-card">

        <div className="dashboard-search-title">

          <span>📍</span>

          <div>

            <strong>
              Search Location
            </strong>

            <p>
              Search any Indian city, town or location
            </p>

          </div>

        </div>

        <div className="dashboard-search-box">

          <input
            type="text"
            value={searchText}
            placeholder="Search Indian city or location..."
            onChange={(event) =>
              setSearchText(event.target.value)
            }
            onKeyDown={handleSearchKeyDown}
          />

          <button
            onClick={handleSearchLocation}
            disabled={searching}
          >
            {searching
              ? "Searching..."
              : "Search"}
          </button>

        </div>

      </div>


      {/* =========================
          ERROR
      ========================= */}

      {error && (
        <div className="dashboard-error">

          ⚠️

          <span>
            {error}
          </span>

        </div>
      )}


      {/* =========================
          BRICS CITIES
      ========================= */}

      <div className="dashboard-cities">

        <div className="dashboard-section-heading">

          <div>

            <span>
              BRICS MONITORING NETWORK
            </span>

            <h2>
              🌐 Major Cities
            </h2>

          </div>

          <p>
            Select a city to view live environmental data
          </p>

        </div>

        <div className="dashboard-city-grid">

          {BRICS_CITIES.map((city) => (

            <button
              key={city.key}
              className={
                selectedCity === city.key
                  ? "dashboard-city active"
                  : "dashboard-city"
              }
              onClick={() =>
                handleCityChange(city.key)
              }
            >

              <span className="city-flag">
                {city.flag}
              </span>

              <span className="city-details">

                <strong>
                  {city.name}
                </strong>

                <small>
                  {city.country}
                </small>

              </span>

              {selectedCity === city.key && (
                <span className="city-selected">
                  ✓
                </span>
              )}

            </button>

          ))}

        </div>

      </div>


      {/* =========================
          CURRENT LOCATION
      ========================= */}

      {location && (

        <div className="dashboard-location-card">

          <div>

            <span className="dashboard-card-label">
              CURRENT MONITORING LOCATION
            </span>

            <h2>
              📍 {location.name}
            </h2>

            <p>
              {location.state
                ? `${location.state}, `
                : ""}

              {location.country || "India"}
            </p>

          </div>

          <div className="dashboard-coordinates">

            <div>

              <span>
                LATITUDE
              </span>

              <strong>
                {Number(
                  location.latitude
                ).toFixed(4)}
              </strong>

            </div>

            <div>

              <span>
                LONGITUDE
              </span>

              <strong>
                {Number(
                  location.longitude
                ).toFixed(4)}
              </strong>

            </div>

          </div>

        </div>

      )}


      {/* =========================
          AIR QUALITY
      ========================= */}

      <div className="dashboard-main-section">

        <div className="dashboard-section-heading">

          <div>

            <span>
              LIVE AIR QUALITY
            </span>

            <h2>
              🌫️ Pollution Overview
            </h2>

          </div>

          <div className="dashboard-status-pill">

            <span></span>

            LIVE DATA

          </div>

        </div>

        <div className="dashboard-kpi-grid">

          <div className="dashboard-kpi primary">

            <div className="kpi-icon">
              🌫️
            </div>

            <div>

              <span>
                AIR QUALITY INDEX
              </span>

              <strong>
                {aqi || "--"}
              </strong>

              <small>
                {aqiStatus}
              </small>

            </div>

          </div>

          <div className="dashboard-kpi">

            <div className="kpi-icon">
              🔬
            </div>

            <div>

              <span>
                PM2.5
              </span>

              <strong>
                {pm25 || "--"}
              </strong>

              <small>
                µg/m³ · {pm25Status}
              </small>

            </div>

          </div>

          <div className="dashboard-kpi">

            <div className="kpi-icon">
              🧪
            </div>

            <div>

              <span>
                PM10
              </span>

              <strong>
                {pm10 || "--"}
              </strong>

              <small>
                µg/m³
              </small>

            </div>

          </div>

          <div className="dashboard-kpi">

            <div className="kpi-icon">
              🏭
            </div>

            <div>

              <span>
                NO₂
              </span>

              <strong>
                {no2 || "--"}
              </strong>

              <small>
                µg/m³
              </small>

            </div>

          </div>

        </div>

        <div className="dashboard-aqi-note">
          AQI shown using the OpenWeather 1–5 air pollution index.
        </div>

      </div>


      {/* =========================
          WEATHER + PREDICTION
      ========================= */}

      <div className="dashboard-two-column">

        {/* WEATHER */}

        <div className="dashboard-panel">

          <div className="dashboard-panel-header">

            <div>

              <span>
                CURRENT CONDITIONS
              </span>

              <h2>
                🌤️ Weather
              </h2>

            </div>

            <div className="panel-icon">
              🌡️
            </div>

          </div>

          <div className="weather-main">

            <strong>
              {temperature}

              {temperature !== "--"
                ? "°C"
                : ""}
            </strong>

            <span>
              Current temperature
            </span>

          </div>

          <div className="weather-details">

            <div>

              <span>
                HUMIDITY
              </span>

              <strong>
                {humidity}

                {humidity !== "--"
                  ? "%"
                  : ""}
              </strong>

            </div>

            <div>

              <span>
                WIND
              </span>

              <strong>
                {windSpeed}
              </strong>

            </div>

            <div>

              <span>
                SO₂
              </span>

              <strong>
                {so2 || "--"}
              </strong>

            </div>

            <div>

              <span>
                O₃
              </span>

              <strong>
                {o3 || "--"}
              </strong>

            </div>

          </div>

        </div>


        {/* PREDICTION */}

        <div className="dashboard-panel">

          <div className="dashboard-panel-header">

            <div>

              <span>
                MACHINE LEARNING
              </span>

              <h2>
                🤖 AI Prediction
              </h2>

            </div>

            <div className="panel-icon">
              🤖
            </div>

          </div>

          {predictionLoading ? (

            <div className="prediction-unavailable">

              <div className="prediction-loading-dot">
                ⏳
              </div>

              <strong>
                Loading AI prediction...
              </strong>

              <small>
                Analyzing current pollution data
              </small>

            </div>

          ) : prediction ? (

            <>

              <div className="prediction-flow">

                <div>

                  <span>
                    CURRENT PM2.5
                  </span>

                  <strong>
                    {pm25}
                  </strong>

                  <small>
                    µg/m³
                  </small>

                </div>

                <div className="prediction-arrow">
                  →
                </div>

                <div className="prediction-highlight">

                  <span>
                    NEXT HOUR
                  </span>

                  <strong>
                    {predictedPM25}
                  </strong>

                  <small>
                    µg/m³
                  </small>

                </div>

              </div>

              <div className="prediction-footer">

                <span>
                  STATUS
                </span>

                <strong>
                  {prediction.status ||
                    "Prediction available"}
                </strong>

                <small>
                  {prediction.model ||
                    "Random Forest"}
                </small>

              </div>

            </>

          ) : (

            <div className="prediction-unavailable">

              <div>
                🤖
              </div>

              <strong>
                AI prediction unavailable
              </strong>

              <small>
                {predictionError ||
                  "Prediction is not available for this location."}
              </small>

            </div>

          )}

        </div>

      </div>


      {/* =========================
          POLLUTION ALERT
      ========================= */}

      <div className="dashboard-feature-section">

        <PollutionAlert
          air={air}
          location={location}
        />

      </div>


      {/* =========================
          MAP
      ========================= */}

      <div className="dashboard-feature-section">

        <div className="dashboard-section-heading">

          <div>

            <span>
              GEOGRAPHICAL MONITORING
            </span>

            <h2>
              🗺️ Pollution Map
            </h2>

          </div>

          <p>
            Environmental conditions around the selected location
          </p>

        </div>

        <div className="dashboard-map-card">

          <Map
            latitude={location?.latitude}
            longitude={location?.longitude}
            location={location}
            air={air}
          />

        </div>

      </div>


      {/* =========================
          POLLUTION CHART
      ========================= */}

      <div className="dashboard-feature-section">

        <div className="dashboard-section-heading">

          <div>

            <span>
              POLLUTION ANALYTICS
            </span>

            <h2>
              📊 Pollution Levels
            </h2>

          </div>

        </div>

        <div className="dashboard-chart-card">

          <PollutionChart
            hotspots={air?.hotspots}
            air={air}
            location={location}
          />

        </div>

      </div>


      {/* =========================
          FORECAST
      ========================= */}

      <div className="dashboard-feature-section">

        <div className="dashboard-section-heading">

          <div>

            <span>
              FORECASTING
            </span>

            <h2>
              📈 Air Quality Forecast
            </h2>

          </div>

        </div>

        <div className="dashboard-chart-card">

          <ForecastChart
            forecast={forecast}
            location={location}
          />

        </div>

      </div>


      {/* =========================
          SMART FEATURES
      ========================= */}

      <div className="dashboard-smart-section">

        <div className="dashboard-section-heading">

          <div>

            <span>
              SMART ENVIRONMENTAL TOOLS
            </span>

            <h2>
              🧠 AI & Citizen Intelligence
            </h2>

          </div>

          <p>
            AI analysis and community-powered environmental monitoring
          </p>

        </div>

        <div className="dashboard-smart-grid">

          {/* AI ASSISTANT */}

          <div className="dashboard-smart-card">
  <div className="smart-card-icon">🧠</div>

  <h3>AI Environmental Assistant</h3>

  <p>
    Ask questions about air quality, pollution,
    weather, PM2.5 and environmental conditions.
  </p>

  <div className="dashboard-ai-box">

    <textarea
      value={aiQuestion}
      onChange={(e) =>
        setAiQuestion(e.target.value)
      }
      placeholder="Ask a question about the environment..."
      rows="3"
    />

    <button
      onClick={askAI}
      disabled={
        aiLoading ||
        !location ||
        !air ||
        !aiQuestion.trim()
      }
    >
      {aiLoading
        ? "🤖 Thinking..."
        : "✨ Ask AI"}
    </button>

    {aiError && (
      <div className="ai-error">
        {aiError}
      </div>
    )}

    {aiAnswer && (
      <div className="ai-answer">
        <div className="ai-answer-title">
          🤖 <strong>AI Answer</strong>
        </div>

        <div className="ai-answer-text">
          {aiAnswer}
        </div>
      </div>
    )}


            </div>

          </div>


          {/* IMAGE ANALYSIS */}

          <div className="dashboard-smart-card">

            <div className="smart-card-icon">
              📷
            </div>

            <h3>
              Pollution Image Analysis
            </h3>

            <p>
              Upload an image and use AI to identify visible
              pollution sources.
            </p>

            <PollutionImageAnalysis />

          </div>

        </div>

      </div>


      {/* =========================
          CITIZEN REPORT
      ========================= */}

      <div className="dashboard-feature-section">

        <div className="dashboard-section-heading">

          <div>

            <span>
              COMMUNITY MONITORING
            </span>

            <h2>
              📢 Citizen Pollution Report
            </h2>

          </div>

          <p>
            Report pollution incidents from your location
          </p>

        </div>

        <CitizenReport
          location={location}
        />

      </div>


      {/* =========================
          ADVANCED ANALYTICS
      ========================= */}

      <div className="dashboard-feature-section">

        <div className="dashboard-section-heading">

          <div>

            <span>
              ADVANCED ANALYTICS
            </span>

            <h2>
              📊 Environmental Analytics
            </h2>

          </div>

          <p>
            Analyze pollution trends and forecast data
          </p>

        </div>

        <div className="dashboard-analytics-card">

          <AdvancedAnalytics
            air={air}
            location={location}
          />

        </div>

      </div>


      {/* =========================
          DATA SOURCES
      ========================= */}

      <div className="dashboard-data-sources">

        <div>

          <span>
            AIR QUALITY
          </span>

          <strong>
            OpenWeather
          </strong>

        </div>

        <div>

          <span>
            WEATHER
          </span>

          <strong>
            OpenWeather
          </strong>

        </div>

        <div>

          <span>
            FORECAST
          </span>

          <strong>
            Open-Meteo
          </strong>

        </div>

        <div>

          <span>
            AI
          </span>

          <strong>
            Gemini
          </strong>

        </div>

        <div>

          <span>
            ML
          </span>

          <strong>
            Random Forest
          </strong>

        </div>

      </div>

    </div>
  );
}

export default Dashboard;